### ISSUE TITLE
less processing trigger not found

### ISSUE THREAD

**Issue by LMSBrubaker** [benjaminkott/packagebuilder#6]
Hello!
I posted my question in stackoverflow. i cant get the less files compiled...
https://stackoverflow.com/questions/46025225/bootstrap-package-sitepackagebuilder-less-files-compiling

**Comment by benjaminkott** [comment]
@LMSBrubaker working on documentation for this, site will contain docs about this in the future.

The automatic less processing is disabled in the packagebuilder for now, since i recommend a normal preprocessing workflow and deploy the generated css code.

You need to have npm and grunt-cli installed in your machine.

Download and install node.js https://nodejs.org/en/
Install Grunt CLI https://gruntjs.com/getting-started

```
cd Build
npm install
grunt css
```
